name: Build & Test

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        GOOS: ["linux", "darwin", "windows"]
        GOARCH: ["amd64", "arm64"]
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
      CGO_ENABLED: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: |
          go vet ./...
          go build ./...

